package com.fulfilment.application.monolith.warehouses.domain.exceptions;

public enum WarehouseErrorCode {
  WAREHOUSE_DATA_REQUIRED,
  BUSINESS_UNIT_CODE_REQUIRED,
  LOCATION_REQUIRED,
  INVALID_CAPACITY,
  INVALID_STOCK,
  STOCK_EXCEEDS_CAPACITY,
  LOCATION_NOT_FOUND,
  LOCATION_WAREHOUSE_LIMIT_REACHED,
  LOCATION_CAPACITY_EXCEEDED,
  DUPLICATE_BUSINESS_UNIT_CODE,
  WAREHOUSE_NOT_FOUND,
  REPLACEMENT_STOCK_MISMATCH,
  WAREHOUSE_ID_NOT_ALLOWED,
  BUSINESS_UNIT_CODE_MISMATCH,
  INVALID_WAREHOUSE_ID
}
